//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_AkmalRentals.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_akmalrentalsEntities : DbContext
    {
        public db_akmalrentalsEntities()
            : base("name=db_akmalrentalsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tb_attendance> tb_attendance { get; set; }
        public virtual DbSet<tb_attendanceStatus> tb_attendanceStatus { get; set; }
        public virtual DbSet<tb_building> tb_building { get; set; }
        public virtual DbSet<tb_category> tb_category { get; set; }
        public virtual DbSet<tb_cleaner> tb_cleaner { get; set; }
        public virtual DbSet<tb_expenses> tb_expenses { get; set; }
        public virtual DbSet<tb_floor> tb_floor { get; set; }
        public virtual DbSet<tb_inventory> tb_inventory { get; set; }
        public virtual DbSet<tb_investor> tb_investor { get; set; }
        public virtual DbSet<tb_landlord> tb_landlord { get; set; }
        public virtual DbSet<tb_payment> tb_payment { get; set; }
        public virtual DbSet<tb_profit> tb_profit { get; set; }
        public virtual DbSet<tb_role> tb_role { get; set; }
        public virtual DbSet<tb_room> tb_room { get; set; }
        public virtual DbSet<tb_share> tb_share { get; set; }
        public virtual DbSet<tb_status> tb_status { get; set; }
        public virtual DbSet<tb_tenant> tb_tenant { get; set; }
        public virtual DbSet<tb_user> tb_user { get; set; }
    }
}
