//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_AkmalRentals.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_expenses
    {
        [DisplayName("Expense ID")]
        public int e_id { get; set; }
        [DisplayName("Type")]
        public string e_Type { get; set; }
        [DisplayName("Date")]
        public System.DateTime e_Date { get; set; }
        [DisplayName("Category")]
        public int e_Category { get; set; }
        [DisplayName("Payment Type")]
        public string e_Payment { get; set; }
        [DisplayName("Detail")]
        public string e_Detail { get; set; }
        [DisplayName("Amount")]
        public double e_Amount { get; set; }
        [DisplayName("Receipt")]
        public string e_Receipt { get; set; }
    
        public virtual tb_category tb_category { get; set; }
    }
}
