//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_AkmalRentals.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_floor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_floor()
        {
            this.tb_cleaner = new HashSet<tb_cleaner>();
            this.tb_inventory = new HashSet<tb_inventory>();
            this.tb_landlord = new HashSet<tb_landlord>();
            this.tb_room = new HashSet<tb_room>();
        }

        [DisplayName("Floor ID")]
        public int y_id { get; set; }
        [DisplayName("Location")]
        public string y_location { get; set; }
        [DisplayName("Address")]
        public string y_address { get; set; }
        [DisplayName("Floor")]
        public string y_floor { get; set; }
        [DisplayName("Description")]
        public string y_desc { get; set; }
        [DisplayName("CCTV QR")]
        public string y_cctvqr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_cleaner> tb_cleaner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_inventory> tb_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_landlord> tb_landlord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_room> tb_room { get; set; }
    }
}
