//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_AkmalRentals.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_investor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_investor()
        {
            this.tb_share = new HashSet<tb_share>();
        }
        [DisplayName("Investor ID")]
        public int i_id { get; set; }
        [DisplayName("Investment Amount")]
        public double i_investment { get; set; }
        [DisplayName("Investment Percentage")]
        public double i_percentage { get; set; }
        [DisplayName("Investment Lot")]
        public int i_lot { get; set; }
    
        public virtual tb_building tb_building { get; set; }
        public virtual tb_user tb_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_share> tb_share { get; set; }
    }
}
