//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_AkmalRentals.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_paylandlord
    {
        public int pl_id { get; set; }
        [Required(ErrorMessage = "The Date field is required.")]
        public System.DateTime pl_Date { get; set; }
        [Required(ErrorMessage = "The Category field is required.")]
        public int pl_Category { get; set; }
        [Required(ErrorMessage = "The Payment field is required.")]
        public string pl_Payment { get; set; }
        [Required(ErrorMessage = "The Landlord Name field is required.")]
        public int pl_LandlordId { get; set; }
        [Required(ErrorMessage = "The Amount field is required.")]
        public double pl_Amount { get; set; }
        public string pl_Receipt { get; set; }
    
        public virtual tb_category tb_category { get; set; }
        public virtual tb_landlord tb_landlord { get; set; }
    }
}
