//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_AkmalRentals.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_profit
    {
        [DisplayName("Profit ID")]
        public int profit_id { get; set; }

        [DisplayName("Profit Amount")]
        public double profit_amount { get; set; }

        [DisplayFormat(DataFormatString = "{0:MMMM yyyy}")]
        [DisplayName("Date")]
        public System.DateTime profit_date { get; set; }

        [DisplayName("Profit AR")]
        public double profit_AR { get; set; }

        [DisplayName("Profit Investor")]
        public double profit_inv { get; set; }

        [DisplayName("Rental Profit")]
        public double profit_lot { get; set; }
    }
}
