//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_AkmalRentals.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_tenant
    {
        [DisplayName("Tenant IC")]
        public string t_ic { get; set; }

        [DisplayName("Name")]
        public string t_name { get; set; }

        [DisplayName("Contact")]
        public string t_contact { get; set; }

        [DisplayName("Emergency Contact")]
        public string t_emergencyContact { get; set; }

        [DisplayName("Check In Date")]
        public System.DateTime t_chkinDate { get; set; }

        [DisplayName("Check Out Date")]
        public System.DateTime t_chkoutDate { get; set; }

        [DisplayName("Room")]
        public int t_room { get; set; }

        [DisplayName("IC Document")]
        public string t_ICdoc { get; set; }

        [DisplayName("No. of Pax")]
        public int t_pax { get; set; }
    
        public virtual tb_room tb_room { get; set; }
    }
}
