using System;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKMALRENTALSYSTEM.Models
{
    public class tb_tenantBase
    {
        public string t_agreement { get; set; }
        public System.DateTime t_chkinDate { get; set; }
        public System.DateTime t_chkoutDate { get; set; }
        public string t_contact { get; set; }
        public string t_emergencyContact { get; set; }
        public string t_ic { get; set; }
        public string t_ICdoc { get; set; }
        public string t_name { get; set; }

        public Nullable<int> t_pax { get; set; }
        public int t_room { get; set; }
    }
}